const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/nguoidungController');
router.post('/login', ctrl.login);
router.post('/register', ctrl.register);
router.put('/:id/profile', ctrl.updateProfile);
router.put('/:id/password', ctrl.changePassword);
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getById);
router.post('/', ctrl.create);
router.put('/:id', ctrl.update);
router.delete('/:id', ctrl.delete);
module.exports = router;
